### PR TITLE
Simplifying installToolbar code

### PR DESCRIPTION
**Pull request by Tosca01**

### CODE REVIEW

**Comment by azhe403** [comment]
@Arpha01 test

**Comment by azhe403** [comment]
@Azhe403 gak pake commit biasa mbah :v

**Comment by Tosca01** [comment]
@Azhe403 mbah kok desainer nya jadi acak kadul ya :v

**Comment by azhe403** [comment]
@Arpha01 mungkin kemarin gara2 bentrok mbah :v 
btw pake 1 branch aja mbah

**Pull request merged**
